config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      root to: "posts#home"

      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/guest_login", to: "sessions#guest_login"
      delete "/logout", to: "sessions#destroy"

      namespace :admin do
        resources :users
      end

      get "/home", to: "posts#home"

      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resource :bookmarks, only: [:create, :destroy]
        resources :replies, only: [:create, :destroy]
      end

      resources :groups, except: :destroy do
        resources :group_users, only: [:create, :update, :destroy]
      end

      resources :notices, only: [:index, :update]
    end
  end
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :sender, class_name: "User", optional: true
  belongs_to :receiver, class_name: "User", optional: true
  belongs_to :post, optional: true
  belongs_to :favorite, optional: true
  belongs_to :reply, optional: true
  belongs_to :group, optional: true
  belongs_to :group_user, optional: true
end

app/controllers/api/v1/notices_controller.rb
module Api
  module V1
    class NoticesController < ApplicationController
      def index
        @notices = current_user.passive_notices.preload(:sender, :group).where.not(sender_id: current_user.id).order(id: :DESC)
      end

      def update
        notice = Notice.find(params[:id])
        notice.update(checked: params[:checked])
        redirect_to notices_path
      end
    end
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
  def post_user(notice)
    Post.find_by(id: notice.post_id).user
  end
end

app/views/notices/index.html.erb
<h1>通知一覧</h1>

<% @notices.each do |notice| %>
  <% if notice.checked? %>
    <% background_color = "bg-light bg-gradient bg-opacity-50" %>
  <% else %>
    <% background_color = "bg-info bg-gradient bg-opacity-50" %>
  <% end %>
  <div class="card mb-3 col-md-8 mx-auto <%= background_color %>">
    <div class="form-inline">
      <span>
        <%= link_to notice.sender.user_name, admin_user_path(notice.sender_id), style: "font-weight: bold;" %>
        さんが，
      </span>
      <% case notice.notice_factor %>
      <% when "favorite" then %>
        <%= link_to "あなたの投稿", post_path(notice.post_id), style: "font-weight: bold;" %>
        をfavoriteしました．
      <% when "reply" then %>
        <% if current_user.id == post_user(notice).id %>
          <%= link_to "あなたの投稿", post_path(notice.post_id), style: "font-weight: bold;" %>
        <% else %>
          <%= link_to "あなたがリプライした#{post_user(notice).user_name}さんの投稿", post_path(notice.post_id), style: "font-weight: bold;" %>
        <% end %>
        にリプライしました．
      <% when "group_invitation" then %>
        <%= link_to "グループ「#{notice.group.group_name}」", group_path(notice.group.id), style: "font-weight: bold;" %>
        にあなたを招待しました．
      <% end %>
      <div class="small text-muted text-end">
        <%= "通知："+time_ago_in_words(notice.created_at)+"前" %>
      </div>
      <div class="small btn-sm w-100 text-muted text-end">
        <%= form_with url: notice_path(notice.id), method: :patch do |f| %>
          <% if notice.checked? %>
            <%= "既読："+time_ago_in_words(notice.updated_at)+"前" %>
            <%= f.submit "未読にする" %>
            <%= f.hidden_field :checked, value: false %>
          <% else %>
            <%= "未読：" %>
            <%= f.submit "既読にする" %>
            <%= f.hidden_field :checked, value: true %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>