config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      root to: "posts#home"

      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/guest_login", to: "sessions#guest_login"
      delete "/logout", to: "sessions#destroy"

      namespace :admin do
        resources :users
      end

      get "/home", to: "posts#home"

      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resource :bookmarks, only: [:create, :destroy]
        resources :replies, only: [:create, :destroy]
      end

      resources :groups, except: :destroy do
        resources :group_users, only: [:create, :update, :destroy]
      end

      resources :notices, only: [:index, :update]
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :group_avatar
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :notices
  has_many :disclosures, dependent: :destroy
  has_many :posts, through: :disclosures

  validates :group_avatar, content_type: { in: %w(image/jpeg image/gif image/png), message: "のファイル形式は，JPEG, GIF, PNGのみ添付可能です．" },
                           size: { less_than: 5.megabytes, message: "のデータ容量は5MB以下として下さい．" }
  validates :group_name, presence: true, uniqueness: true, on: :create

  # グループにユーザーが招待されたことを通知するnoticeレコードを生成する．
  # 通知受信者はグループに招待されたユーザーとする．
  def create_group_invitation_notice(group_users, user)
    group_users.each do |group_user|
      user.active_notices.create(receiver_id: group_user.user_id, group_user_id: group_user.id, group_id: id, notice_factor: "group_invitation")
    end
  end
end

app/controllers/api/v1/groups_controller.rb
module Api
  module V1
    class GroupsController < ApplicationController
      before_action :group_user?, except: [:new, :create, :index]

      def index
        @groups = Group.preload(:users, group_avatar_attachment: :blob)
      end

      def new
        @group = Group.new
        @users = User.all
      end

      def create
        @group = Group.new(group_params)
        @users = User.all

        if @group.save # post保存時に，collection_check_boxesメソッドによりgroup_usersテーブルのレコードが生成．

          # グループ作成者(group_founder)をデフォルトでグループの所属メンバーにする．
          group_founder = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
          group_founder.update(accepted: true)

          # group_userの作成に合わせて通知を発行する．
          @group_users = GroupUser.where(group_id: @group.id)
          @group.create_group_invitation_notice(@group_users, current_user)

          flash[:success] = "グループ「#{@group.group_name}」を作成しました．"
          redirect_to group_path(@group.id)
        else
          flash.now[:danger] = "グループを作成できませんでした．"
          render :new
        end
      end

      def show
        @group = Group.preload(:users, group_avatar_attachment: :blob).find(params[:id])
        @users = User.all
      end

      def edit
        @group = Group.find(params[:id])
      end

      def update
        @group = Group.find(params[:id])
        if @group.update(group_params)
          flash[:success] = "「#{@group.group_name}」を更新しました．"
          redirect_to group_path(@group.id)
        else
          flash.now[:danger] = "グループを更新できませんでした．"
          render :edit
        end
      end

      private

      def group_params
        params.require(:group).permit(:group_name, :group_profile, :group_avatar, :user_id, user_ids: [])
      end

      def group_user?
        group = Group.find(params[:id])
        group_user = group.group_users.find_by(group_id: group.id, user_id: current_user.id)
        redirect_to groups_path if group_user.blank?
      end
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_user(group, user)
    GroupUser.find_by(group_id: group.id, user_id: user.id)
  end
end

app/views/groups/edit.html.erb
<% if @group.errors.present? %>
  <% @group.errors.full_messages.each do |error_message| %>
    <ul>
      <li><%= error_message %></li>
    </ul>
  <% end %>
<% end %>

<h1>グループ情報編集</h1>

<%= form_with model: @group do |f| %>
  <ul class="nav justify-content-center">
    <li><%= link_to "グループ一覧に戻る", groups_path, class: "btn btn-primary" %></li>
    <li><%= link_to "グループ詳細・メンバー編集に戻る", group_path(@group), class: "btn btn-primary" %></li>
    <li><%= f.submit "グループ情報を更新する", class: "btn btn-primary" %></li>
  </ul>
  <div class="form-group">
    <%= f.label :group_name, "グループ名" %>
    <%= f.text_field :group_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :group_avatar, "アイコン" %>
    <%= f.file_field :group_avatar, accept: "image/jpeg,image/gif,image/png", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :group_profile, "グループ紹介" %>
    <%= f.text_field :group_profile, class: "form-control" %>
  </div>
<% end %>

app/views/groups/index.html.erb
<h1>グループ一覧</h1>

<ul class="nav justify-content-center">
  <li><%= link_to "ホームに戻る", home_path, class: "btn btn-primary" %></li>
  <li><%= link_to "グループを新設する", new_group_path, class: "btn btn-primary" %></li>
</ul>

<div class="row">
  <div class="col-md-6">
    <h3>所属グループ</h3>
    <% @groups.each do |group| %>
      <% if group_user(group, current_user).present? %>
        <% if group_user(group, current_user).accepted? %>
          <%= link_to group_path(group.id) do%>
            <small class="card">
              <div class="card-header">
                <p class="card-title"><%= group.group_name %></p>
                <p class="card-text">
                  <p class="text-muted">
                    <%= "投稿：#{I18n.localize group.created_at, format: :long}" %>
                    <%= "更新：#{I18n.localize group.updated_at, format: :long}" %>
                  </p>
                </p>
              </div>
              <%= image_tag group.group_avatar.variant(resize:'100x100'), class: "img-fluid" if group.group_avatar.attached? %>
              <div class="card-body">
                <p class="card-text"><%= group.group_profile %></p>
                <div>
                  所属メンバー：
                  <% group.users.each do |user| %>
                    <%= "#{user.user_name}，" if group_user(group, user).accepted? %>
                  <% end %>
                </div>
                <div>
                  招待中メンバー：
                  <% group.users.each do |user| %>
                    <%= "#{user.user_name}，" unless group_user(group, user).accepted? %>
                  <% end %>
                </div>
              </div>
            </small>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h3>招待されているグループ</h3>
    <% @groups.each do |group| %>
      <% if group_user(group, current_user).present? %>
        <% unless group_user(group, current_user).accepted? %>
          <%= link_to group_path(group.id) do%>
            <small class="card">
              <div class="card-header">
                <p class="card-title"><%= group.group_name %></p>
                <p class="card-text">
                  <p class="text-muted">
                    <%= "投稿：#{I18n.localize group.created_at, format: :long}" %>
                    <%= "更新：#{I18n.localize group.updated_at, format: :long}" %>
                  </p>
                </p>
              </div>
              <%= image_tag group.group_avatar.variant(resize:'100x100'), class: "img-fluid" if group.group_avatar.attached? %>
              <div class="card-body">
                <p class="card-text"><%= group.group_profile %></p>
                <div>
                  所属メンバー：
                  <% group.users.each do |user| %>
                    <%= "#{user.user_name}，" if group_user(group, user).accepted? %>
                  <% end %>
                </div>
                <div>
                  招待中メンバー：
                  <% group.users.each do |user| %>
                    <%= "#{user.user_name}，" unless group_user(group, user).accepted? %>
                  <% end %>
                </div>
              </div>
            </small>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<% if @group.errors.present? %>
  <% @group.errors.full_messages.each do |error_message| %>
    <ul>
      <li><%= error_message %></li>
    </ul>
  <% end %>
<% end %>

<h1>グループ作成</h1>

<%= form_with model: @group do |f| %>
  <ul class="nav justify-content-center">
    <li><%= link_to "グループ一覧に戻る", groups_path, class: "btn btn-primary" %></li>
    <li><%= f.submit "グループを登録する", class: "btn btn-primary" %></li>
  </ul>
  <div class="form-group">
    <%= f.label :group_name, "グループ名" %>
    <%= f.text_field :group_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :group_avatar, "アイコン" %>
    <%= f.file_field :group_avatar, accept: "image/jpeg,image/gif,image/png", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :group_profile, "グループ紹介" %>
    <%= f.text_field :group_profile, class: "form-control" %>
  </div>
  <div class="field">
    <h6>ユーザー一覧（招待するユーザーを選択してください．グループ作成後にユーザー改廃可能です．）</h6>
    <div class="row">
      <%= f.collection_check_boxes(:user_ids, @users, :id, :user_name) do |b| %>
        <% if b.object.id == current_user.id %>
          <div class="col-md-3 bg-success">
            <%= image_tag b.object.user_avatar, size: "32x32", class: "rounded-circle me-2" if b.object.user_avatar.attached? %>
            <%= b.object.user_name %>
            <option disabled><%= b.check_box checked: true %></option>
          </div>
        <% else %>
          <div class="col-md-3 bg-info">
            <%= image_tag b.object.user_avatar, size: "32x32", class: "rounded-circle me-2" if b.object.user_avatar.attached? %>
            <%= b.object.user_name %>
            <%= b.check_box %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<h1>グループ詳細・メンバー編集</h1>

<% if group_user(@group, current_user) %>
  <ul class="nav justify-content-center">
    <% unless group_user(@group, current_user).accepted? %>
      <li><h4 class="text-info"><%= "#{@group.group_name}に招待されています！" %></h4></li>
      <li>
        <%= form_with url: group_group_user_path(@group.id, group_user(@group, current_user).id), method: :patch do |f| %>
          <%= f.hidden_field :accepted, value: true %>
          <%= f.submit "参加する", class: "btn btn-primary" %>
        <% end %>
      </li>
      <li><%= link_to "参加しない", group_group_user_path(@group.id, group_user(@group, current_user).id), method: :delete, data: {confirm: "投稿を削除しますか？"}, class: "btn btn-primary" %></li>
    <% else %>
      <li><%= link_to "グループ情報を編集する", edit_group_path(@group.id), class: "btn btn-primary" %></li>
    <% end %>
    <li><%= link_to "グループ一覧に戻る", groups_path, class: "btn btn-primary" %></li>
  </ul>
<% end %>

<div class="row">
  <div class="card">
    <div class="row g-0">
      <div class="col-md-4 img-fluid">
        <%= image_tag @group.group_avatar.variant(resize:'200x200') if @group.group_avatar.attached? %>
      </div>
      <div class="col-md-8">
        <div class="card-header">
          <h3 class="card-title"><%= @group.group_name %></h3>
          <p class="card-text">
            <p class="text-muted">
              <%= "作成：#{I18n.localize @group.created_at, format: :long}" %>
              <%= "更新：#{I18n.localize @group.updated_at, format: :long}" %>
            </p>
          </p>
        </div>
        <div class="card-body">
          <p class="card-text"><%= @group.group_profile %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h3>所属メンバー</h3>
    <div class="row">
      <% @group.users.each do |user| %>
        <% if group_user(@group, user).accepted? %>
          <%= form_with url: group_group_user_path(@group.id, group_user(@group, user).id), method: :delete do |f| %>
            <div class="card mb-3 col-md-6 img-fluid">
              <%= link_to admin_user_path(user.id), class: "nav-link link-info" do %>
                <%= image_tag user.user_avatar, size: "32x32", class: "rounded-circle me-2" if user.user_avatar.attached? %>
                <strong><%= user.user_name %></strong>
              <% end %>
              <%= f.submit "メンバーから削除する" if group_user(@group, current_user)&.accepted? %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <h3>招待中メンバー</h3>
    <div class="row">
      <% @group.users.each do |user| %>
        <% unless group_user(@group, user).accepted? %>
          <%= form_with url: group_group_user_path(@group.id, group_user(@group, user).id), method: :delete do |f| %>
            <div class="card mb-3 col-md-6 img-fluid">
              <%= link_to admin_user_path(user.id), class: "nav-link link-info" do %>
                <%= image_tag user.user_avatar, size: "32x32", class: "rounded-circle me-2" if user.user_avatar.attached? %>
                <strong><%= user.user_name %></strong>
              <% end %>
              <%= f.submit "招待を取り消す" if group_user(@group, current_user)&.accepted? %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md">
    <h3>その他ユーザー</h3>
    <div class="row">
      <% @users.each do |user| %>
        <% unless group_user(@group, user).present? %>
          <%= form_with url: group_group_users_path(@group.id), method: :post do |f| %>
            <div class="card mb-3 col-md-3 img-fluid">
              <%= link_to admin_user_path(user.id), class: "nav-link link-info" do %>
                <%= image_tag user.user_avatar, size: "32x32", class: "rounded-circle me-2" if user.user_avatar.attached? %>
                <strong><%= user.user_name %></strong>
              <% end %>
              <%= f.hidden_field :group_id, value: @group.id %>
              <%= f.hidden_field :user_id, value: user.id %>
              <%= f.hidden_field :accepted, value: false %>
              <%= f.submit "ユーザーを招待する" if group_user(@group, current_user)&.accepted? %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>