config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      root to: "posts#home"

      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/guest_login", to: "sessions#guest_login"
      delete "/logout", to: "sessions#destroy"

      namespace :admin do
        resources :users
      end

      get "/home", to: "posts#home"

      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resource :bookmarks, only: [:create, :destroy]
        resources :replies, only: [:create, :destroy]
      end

      resources :groups, except: :destroy do
        resources :group_users, only: [:create, :update, :destroy]
      end

      resources :notices, only: [:index, :update]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :post_images
  belongs_to :user
  belongs_to :map
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :replies, dependent: :destroy
  has_many :notices, dependent: :destroy
  has_many :disclosures, dependent: :destroy
  has_many :groups, through: :disclosures

  validates :post_images, content_type: { in: %w(image/jpeg image/gif image/png), message: "のファイル形式は，JPEG, GIF, PNGのみ添付可能です．" },
                          size: { less_than: 5.megabytes, message: "のデータ容量は5MB以下として下さい．" }

  # tagを生成，編集するメソッド
  def create_tags(entered_tags)
    existing_tags = tags.pluck(:tag_name) unless tags.nil?

    # フォームから削除したタグのレコードをdelete
    old_tags = existing_tags - entered_tags
    old_tags.each do |old_tag|
      Tag.find_by(tag_name: old_tag).delete
    end

    # フォームに新規入力したタグのレコードを生成
    new_tags = entered_tags - existing_tags
    new_tags.each do |new_tag|
      tags << Tag.find_or_create_by(tag_name: new_tag)
    end
  end

  # 投稿に紐つくグループを編集するメソッド
  def set_groups(post, newly_set_group_ids)
    # 設定から外されたグループは投稿との紐付きを解消する．
    existing_group_ids = post.groups.ids
    excluded_group_ids = existing_group_ids - newly_set_group_ids
    excluded_group_ids.each do |excluded_group_id|
      Disclosure.find_by(post_id: post.id, group_id: excluded_group_id).delete
    end

    # 新たに設定されたグループを投稿に紐つける．
    newly_set_group_ids.each do |newly_set_group_id|
      Disclosure.find_or_create_by(post_id: post.id, group_id: newly_set_group_id)
    end
  end

  #! # ログインユーザーが閲覧できる投稿を抽出するメソッド
  # def self.extract_posts(user, posts, all_posts)
  #   all_posts.each do |post|
  #     if post.user_id == user.id
  #       # current_userの投稿であれば閲覧できる．
  #       posts << post
  #     else
  #       post.groups.preload(:group_users).each do |group|
  #         group.group_users.each do |group_user|
  #           if group_user.accepted? && (group_user.user_id == user.id)
  #             # 他ユーザーの投稿のうち，公開先グループにcurrent_userが所属している投稿であれば閲覧できる．
  #             posts << post
  #           end
  #         end
  #       end
  #     end
  #   end
  # end

  # 検索条件を編成するメソッド
  def self.search(search_params, user)
    return all if search_params.blank?
    return all if search_params[:search_method] == "all_posts"
    if search_params[:search_method].blank? && search_params[:searched]
      return all
    end

    # whereメソッドにセットする条件と値を格納する配列．
    conditions = []
    values = []

    # キーワード検索．フォームへの入力値をconditionsとvaluesにセット．検索条件毎に同様の処理を以下で実行．
    if search_params[:keyword].present?
      keywords = search_params[:keyword].split(/[,| |，|、|　]/)
      conditions << keywords.map { |keyword| "(comment LIKE ? OR description LIKE ? OR reply LIKE ?)" }.join(" OR ")
      values.concat(keywords.flat_map { |keyword| ["%#{keyword}%", "%#{keyword}%", "%#{keyword}%"] })
    end

    # 日付検索．
    if search_params[:start_date].present? && search_params[:end_date].present?
      conditions << "(memorized_on >= ? AND memorized_on <= ?)"
      values.concat([search_params[:start_date], search_params[:end_date]])
    elsif search_params[:start_date].present?
      conditions << "memorized_on >= ?"
      values << search_params[:start_date]
    elsif search_params[:end_date].present?
      conditions << "memorized_on <= ?"
      values << search_params[:end_date]
    end

    # ロケーション検索
    if search_params[:locations].compact_blank.present?
      conditions << "maps.location IN (?)"
      values << search_params[:locations].compact_blank
    end

    # タグ検索
    if search_params[:tag_names].compact_blank.present?
      conditions << "tags.tag_name IN (?)"
      values << search_params[:tag_names].compact_blank
    end

    # 公開範囲検索
    if search_params[:group_names].compact_blank.present?
      if search_params[:group_names].include?("非公開")
        # "非公開"が選択された場合は，グループに紐つかない投稿を取得．
        conditions << "(groups.id IS NULL OR groups.group_name IN (?))"
      else
        conditions << "groups.group_name IN (?)"
      end
      values << search_params[:group_names].compact_blank
    end

    # 投稿者検索
    if search_params[:user_names].compact_blank.present?
      conditions << "users.user_name IN (?)"
      values << search_params[:user_names].compact_blank
    end

    # お気に入り登録有無検索
    if search_params[:favorites] == "favorited_posts"
      conditions << "favorites.user_id = ?"
      values << user.id
    end

    # ブックマーク有無検索
    if search_params[:bookmarks] == "bookmarked_posts"
      conditions << "bookmarks.user_id = ?"
      values << user.id
    end

    # 検索方式(and, or)別にwhereメソッドを設定．
    if search_params[:search_method] == "and"
      left_outer_joins(:replies, :map, :tags, :groups, :favorites, :bookmarks).where(conditions.join(" AND "), *values)
    elsif search_params[:search_method] == "or"
      left_outer_joins(:replies, :map, :tags, :groups, :favorites, :bookmarks).where(conditions.join(" OR "), *values)
    end
  end

  # 投稿に紐つくmapを抽出するメソッド
  def self.extract_maps(posts, maps)
    posts.each do |post|
      maps << post.map if post.map&.location.present?
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      #! before_action :show_permission_required, only: :show
      #! before_action :edit_permission_required, only: :edit
      #! before_action :delete_permission_required, only: :destroy

      def home
        # ユーザーの閲覧可能な投稿を配列で取得し，配列からActiveRecordを取得する．
        posts_viewed_by_current_user = []
        #! Post.extract_posts(current_user, posts_viewed_by_current_user, Post.all)
        @posts_viewed_by_current_user = Post.where(id: posts_viewed_by_current_user.map(&:id))

        # 上記で取得した投稿に紐つく情報を抽出し，検索フォームを生成する．
        @users = @posts_viewed_by_current_user.eager_load(:user).map(&:user).uniq
        @tags = @posts_viewed_by_current_user.preload(:tags).map(&:tags).flatten.compact_blank.uniq
        @groups = @posts_viewed_by_current_user.preload(:groups).map(&:groups).flatten.compact_blank.uniq
        @groups << Group.find_or_create_by(group_name: "非公開") # 検索フォームに"非公開"を表示させる．
        posts_maps = []
        Post.extract_maps(@posts_viewed_by_current_user.eager_load(:map), posts_maps)
        @maps = posts_maps.compact_blank.uniq

        # 検索後の投稿一覧を取得する．
        @search_params = post_search_params
        @posts = @posts_viewed_by_current_user.
          eager_load(:user, :map).
          preload(:disclosures, :groups, :post_tags, :tags, post_images_attachments: :blob).
          search(@search_params, current_user).
          order(created_at: :desc)

        # 検索後の投稿に紐つくマップ情報を取得する．
        posts_maps = []
        Post.extract_maps(@posts.eager_load(:map), posts_maps)
        maps = posts_maps.compact_blank.uniq
        #! gon.places = Map.where(id: maps.map(&:id))

        #! 以下，暫定的に全データを送信している．開発が進んだら，適切に絞り込む．
        postss = Post.all.order(created_at: :desc)
        userss = User.all
        mapss = Map.all
        post_tagss = PostTag.all
        tagss = Tag.all
        favoritess = current_user.favorites
        favoritess_all = Favorite.all #! 閲覧可能なpostに対応するfavoriteレコードだけ抽出すること．
        bookmarkss = current_user.bookmarks
        repliess = Reply.all

        #! users_with_avatarの取得はモデルメソッドに切り出す．
        users_with_avatar = userss.map do |user|
          if user.user_avatar.attached?
            user.attributes.merge(user_avatar: url_for(user.user_avatar))
          else
            user.attributes.merge(user_avatar: nil)
          end
        end
        #! post_with_imagesの取得はモデルメソッドに切り出す．
        post_with_images = postss.map do |post|
          if post.post_images.attached?
            images_urls = post.post_images.map { |image| url_for(image) }
            post.attributes.merge(post_images: images_urls, blobs: post.post_images.blobs)
          else
            post.attributes.merge(post_images: nil, blobs: nil)
          end
        end
        render json: {
          posts: post_with_images,
          users: users_with_avatar,
          maps: mapss,
          post_tags: post_tagss,
          tags: tagss,
          favorites: favoritess,
          favorites_all: favoritess_all,
          bookmarks: bookmarkss,
          replies: repliess,
        }, status: :ok
      end

      def index
        # ユーザーの閲覧可能な投稿を配列で取得し，配列からActiveRecordを取得する．
        posts_viewed_by_current_user = []
        Post.extract_posts(current_user, posts_viewed_by_current_user, Post.all)
        @posts = Post.
          eager_load(:user, :map).
          preload(:disclosures, :groups, post_images_attachments: :blob).
          where(id: posts_viewed_by_current_user.map(&:id)).
          order(created_at: :desc)
      end

      def new
        @post = Post.new
        @groups = current_user.group_users.where(accepted: true).eager_load(:group).map(&:group)
      end

      def create
        map = Map.find_or_create_by(location: post_location_params[:location])
        post = current_user.posts.new(post_params.merge(map_id: map.id))

        if post.save # post保存時に，collection_check_boxesメソッドによりdisclosuresテーブルのレコードを生成している．
          # 投稿にタグを付ける．
          if post_tag_params[:tag_name].present?
            entered_tags = post_tag_params[:tag_name].split(/[,| |，|、|　]/)
            tags = post.create_tags(entered_tags)
          end

          # 投稿に画像を紐つける．
          if post_images_params[:post_images]
            # post.post_images.purge
            post.post_images.attach(post_images_params[:post_images])
          end

          #! post_with_imagesの取得はモデルメソッドに切り出す．
          if post.post_images.attached?
            images_urls = post.post_images.map { |image| url_for(image) }
            post_with_images = post.attributes.merge(post_images: images_urls)
          else
            post_with_images = post.attributes.merge(post_images: nil)
          end

          render json: {
            post: post_with_images,
            map: map,
            tag: tags,
            message: "思い出を投稿しました．",
          }, status: :created
        else
          render json: { error_messages: post.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def show
        @post = Post.preload(post_images_attachments: :blob).find(params[:id])
        @reply = Reply.new
        @replies = @post.replies.eager_load(:user)
        gon.place = @post.map
      end

      def edit
        @post = Post.find(params[:id])
        @location = @post.map.location if @post.map.present?
        @tag_list = @post.tags.distinct.pluck(:tag_name).join(",")
        @groups = current_user.group_users.where(accepted: true).eager_load(:group).map(&:group)
      end

      def update
        post = Post.find(params[:id])
        # 投稿の開示先グループを編集する．
        # newly_set_group_ids = post_params[:group_ids]
        # post.set_groups(post, newly_set_group_ids)

        # 投稿のタグを編集する．
        if post_tag_params[:tag_name].present?
          entered_tags = post_tag_params[:tag_name].split(/[,| |、|　]/)
          tags = post.create_tags(entered_tags)
        end

        # 投稿のロケーションを編集する．
        if post_location_params[:location].present?
          map = post.map.update(location: post_location_params[:location])
        end

        if post.update(post_params)

          # binding.pry

          if post_images_params[:images_blob_ids]
            # binding.pry
            # token = post_images_params[:images_blob_ids][0].split("/")[-2]
            # blob = ActiveStorage::Blob.find_by(key: token)
            blob_ids = post_images_params[:images_blob_ids]
            post_images = post.post_images.attachments.where(blob_id: blob_ids)
            post_images.purge
            post.post_images.attach
          end

          if post_images_params[:post_images]
            post.post_images.attach(post_images_params[:post_images])
          end

          #! post_with_imagesの取得はモデルメソッドに切り出す．
          if post.post_images.attached?
            images_urls = post.post_images.map { |image| url_for(image) }
            post_with_images = post.attributes.merge(post_images: images_urls, blobs: post.post_images.blobs)
          else
            post_with_images = post.attributes.merge(post_images: nil, blobs: nil)
          end
          render json: {
            post: post_with_images,
            map: map,
            tag: tags,
            message: "投稿を更新しました.",
          }, status: :created
        else
          render json: { error_messages: post.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def destroy
        post = Post.find(params[:id])
        post.destroy
        render json: { message: "投稿を削除しました." }, status: :ok
      end

      private

      def post_params
        params.permit(:comment, :memorized_on, :description, group_ids: [])
        # params.permit(:comment, :memorized_on, :description, post_images: [], group_ids: [])
        # params.require(post).permit(:comment, :memorized_on, :description, post_images: [], group_ids: [])
      end

      def post_images_params
        params.permit(post_images: [], images_blob_ids: [])
      end

      def post_location_params
        params.permit(:location)
      end

      def post_tag_params
        params.permit(:tag_name)
      end

      def post_search_params
        params.fetch(:search, {}).permit(:keyword, :start_date, :end_date, :favorites, :bookmarks, :search_method, :searched, locations: [], tag_names: [], group_names: [], user_names: [])
      end

      def show_permission_required
        @post = Post.find(params[:id])

        # 投稿の公開先グループにcurrent_userが所属しているかどうかを判定する．判定結果としての論理値を配列に格納．
        group_affilication_status_of_current_user = []
        @post.groups.each do |group|
          group.group_users.each do |group_user|
            group_affilication_status_of_current_user << (group_user.accepted? && (group_user.user_id == current_user.id))
          end
        end

        # current_userの投稿であれば投稿詳細を閲覧できる．
        # 他ユーザーの投稿のうち，公開先グループにcurrent_userが所属している投稿であれば詳細を閲覧できる．
        # 上記に該当しない場合は投稿詳細の閲覧できない．
        if @post.user_id == current_user.id
        elsif group_affilication_status_of_current_user.any?
        else
          redirect_to home_path
        end
      end

      def edit_permission_required
        @post = Post.find(params[:id])
        redirect_to post_path(@post.id) unless @post.user_id == current_user.id
      end

      def delete_permission_required
        @post = Post.find(params[:id])
        if @post.user_id == current_user.id || current_user.admin?
        else
          redirect_to post_path(@post.id)
        end
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  # 検索時にフラッシュメッセージを発行するメソッド
  def flash_message(search_params)
    if search_params.blank?
    elsif search_params[:search_method] == "all_posts"
      flash.now[:info] = "全ての投稿を表示しました．"
    elsif search_params[:search_method].blank? && search_params[:searched]
      flash.now[:danger] = "検索方式「AND, OR検索」を選択してください．"
    elsif search_params[:start_date].present? && search_params[:end_date].present?
      if search_params[:start_date] >= search_params[:end_date]
        flash.now[:danger] = "期間の終了日を開始日より遅く設定してください．"
      end
    else
      flash.now[:success] = "指定の条件で投稿を絞り込みました．"
    end
  end

  def favorited_by?(post, user)
    Favorite.where(post_id: post.id, user_id: user.id)
  end

  def bookmarked_by?(post, user)
    Bookmark.where(post_id: post.id, user_id: user.id)
  end

  def replies_count(post)
    Reply.where(post_id: post.id).size
  end

  def disclosed_user(post)
    disclosed_user = []
    post.groups.preload(:group_users, :users).each do |group|
      group.users.each do |user|
        disclosed_user << user.user_name
      end
    end
    disclosed_user.uniq
  end
end

app/views/posts/_home_posts.html.erb
<div class="card mb-3 col-md-6">
  <div class="row g-0">
    <div class="col-md-4 img-fluid">
      <% if post.post_images.attached? %>
        <% post.post_images.each do |post_image| %>
          <%= image_tag post_image.variant(resize:'100x100') %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-header">
        <h5 class="card-title"><%= post.user.user_name %></h5>
        <p class="card-text">
          <small class="text-muted">
            <%= "投稿：#{I18n.localize post.created_at, format: :long}" %>
            <%= "更新：#{I18n.localize post.updated_at, format: :long}" %>
          </small>
        </p>
      </div>
      <div class="card-body">
        <p class="card-text"><%= post.comment %></p>
        <p class="card-text"><%= "思い出の日付：#{post.memorized_on}" %></p>
        <p class="card-text"><%= "思い出のロケーション：#{post.map.location}" if post.map.present? %></p>
        <p class="card-text">タグ：
          <% post.tags.distinct.each do |tag| %>
            <span class="bg-info bg-opacity-75 border border-dark rounded"><%= tag.tag_name %></span>
          <% end %>
        </p>
        <p class="card-text">公開範囲：
          <% if post.groups.present? %>
            <% post.groups.each do |group| %>
              <span class="bg-info bg-opacity-75 border border-dark rounded">
                <%= group.group_name %>
              </span>
            <% end %>
          <% else %>
            <span class="bg-info bg-opacity-75 border border-dark rounded">
              <%= "非公開" %>
            </span>
          <% end %>
        </p>
      </div>
      <div class="card-footer">
        <div class="card-text">
          <% if favorited_by?(post, current_user).present? %>
            <%= link_to post_favorites_path(post.id), method: :delete do %>
              <i class="fa fa-thumbs-up fa-lg fa-fw" aria-hidden="true" style="color: red;"></i><%= favorited_by?(post, current_user).size %>
            <% end %>
          <% else %>
            <%= link_to post_favorites_path(post.id), method: :post do %>
              <i class="fa fa-thumbs-up fa-lg fa-fw" aria-hidden="true" style="color: gray;"></i><%= favorited_by?(post, current_user).size %>
            <% end %>
          <% end %>
          <% if bookmarked_by?(post, current_user).present? %>
            <%= link_to post_bookmarks_path(post.id), method: :delete do %>
              <i class="fa fa-bookmark fa-lg fa-fw" aria-hidden="true" style="color: blue;"></i>
            <% end %>
          <% else %>
            <%= link_to post_bookmarks_path(post.id), method: :post do %>
              <i class="fa fa-bookmark fa-lg fa-fw" aria-hidden="true" style="color: gray;"></i>
            <% end %>
          <% end %>
          <%= link_to "投稿詳細/リプライ(#{replies_count(post)})", post_path(post.id), class: "card-link link-info text-decoration-none" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% if @post.errors.present? %>
  <% @post.errors.full_messages.each do |error_message| %>
    <ul>
      <li><%= error_message %></li>
    </ul>
  <% end %>
<% end %>

<h1>新規投稿</h1>

<%= form_with model: @post do |f| %>
  <ul class="nav justify-content-center">
    <li><%= link_to "ホームに戻る", home_path, class: "btn btn-primary" %></li>
    <li><%= f.submit "投稿する", class: "btn btn-primary" %></li>
  </ul>
  <div class="form-group">
    <%= f.label :comment, "コメント" %>
    <%= f.text_area :comment, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :memorized_on, "思い出の日付" %>
    <%= f.date_field :memorized_on, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location, "思い出のロケーション" %>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tag_name, "タグ（複数タグ登録は，単語間にコンマ[,]またはスペースを挿入．）" %>
    <%= f.text_field :tag_name, placeholder: "複数タグ登録は，単語間にコンマ[,]またはスペースを挿入．", class: "form-control" %>
  </div>
  <div class="form-group">
    <h6>公開範囲（公開先グループを選択してください．未選択で非公開にできます．）</h6>
    <%= f.collection_check_boxes(:group_ids, @groups, :id, :group_name) do |b| %>
      <span class="bg-success">
        <%= b.check_box %>
        <%= image_tag b.object.group_avatar, size: "32x32", class: "rounded-circle me-2" if b.object.group_avatar.attached? %>
        <%= b.object.group_name %>
      </span>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :post_images, "思い出の画像" %>
    <%= f.file_field :post_images, multiple: true, class: "form-control", accept: "image/jpeg,image/gif,image/png" %>
  </div>
  <div class="form-group">
    <%= f.label :description, "詳細・補足" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>

<ul class="nav justify-content-center">
  <li><%= link_to "ホームに戻る", home_path, class: "btn btn-primary" %></li>
  <li><%= link_to "画像一覧へ戻る", posts_path, class: "btn btn-primary" %></li>
  <% if @post.user_id == current_user.id %>
    <li><%= link_to "投稿を編集する", edit_post_path(@post.id), class: "btn btn-primary" %></li>
    <li><%= link_to "投稿を削除する", post_path(@post.id), method: :delete, data: {confirm: "投稿を削除しますか？"}, class: "btn btn-primary" %></li>
  <% elsif @post.user_id == current_user.id || current_user.admin? %>
    <li><%= link_to "投稿を削除する", post_path(@post.id), method: :delete, data: {confirm: "投稿を削除しますか？"}, class: "btn btn-primary" %></li>
  <% end %>
</ul>

<h3>思い出Map</h3>
<div id="map"></div>
<script>
function initMap(){
  let markerData = gon.place

  // 初期表示の中心を東京駅に指定．
  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.68123620000001, lng: 139.7671248},
    zoom: 5,
  })

  // マーカーの表示．
  marker = new google.maps.Marker({
    map: map,
    position: { lat: markerData['latitude'], lng: markerData['longitude'] }
  })

  // マーカーの吹き出し表示．
  infoWindow = new google.maps.InfoWindow({
    content: `<a href="#">${markerData['location']}</a>`
  })

  // マーカークリック時に吹き出しを表示.
  marker.addListener('click', function() {
    infoWindow.open(map, marker);
  })
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap" async defer></script>

<br>

<table class="table table-striped">
  <tr>
    <th><%= "投稿者" %></th>
    <td><%= @post.user.user_name %></td>
  </tr>
  <tr>
    <th><%= "投稿日時" %></th>
    <td><%= I18n.localize @post.created_at, format: :long %></td>
  </tr>
  <tr>
    <th><%= "更新日時" %></th>
    <td><%= I18n.localize @post.updated_at, format: :long %></td>
  </tr>
  <tr>
    <th><%= "コメント" %></th>
    <td><%= @post.comment %></td>
  </tr>
  <tr>
    <th><%= "思い出の日付" %></th>
    <td><%= @post.memorized_on %></td>
  </tr>
  <tr>
    <th><%= "思い出のロケーション" %></th>
    <td><%= @post.map.location if @post.map.present? %></td>
  </tr>
  <tr>
    <th><%= "タグ" %></th>
    <td>
      <% @post.tags.distinct.each do |tag| %>
        <span class="bg-info bg-opacity-75 border border-dark rounded"><%= tag.tag_name %></span>
      <% end %>
    </td>
  </tr>
  <tr>
    <th><%= "公開範囲" %></th>
    <td>
      <% if @post.groups.present? %>
        <% @post.groups.each do |group| %>
          <span class="bg-info bg-opacity-75 border border-dark rounded">
            <%= group.group_name %>
          </span>
        <% end %>
      <% else %>
        <span class="bg-danger bg-opacity-75 border border-dark rounded">
          <%= "非公開" %>
        </span>
      <% end %>
    </td>
  </tr>
  <tr>
  <th><%= "公開先ユーザー" %></th>
    <td>
      <% if @post.groups.present? %>
        <% disclosed_user(@post).each do |user| %>
          <span class="bg-info bg-opacity-75 border border-dark rounded">
            <%= user %>
          </span>
        <% end %>
      <% else %>
        <span class="bg-danger bg-opacity-75 border border-dark rounded">
          <%= "投稿者のみ閲覧可能" %>
        </span>
      <% end %>
    </td>
  </tr>
  <tr>
    <th><%= "思い出の画像" %></th>
    <td>
      <div class="col-md-4 img-fluid">
        <% if @post.post_images.attached? %>
          <% @post.post_images.each do |post_image| %>
            <%= image_tag post_image.variant(resize:'200x200') %>
          <% end %>
        <% end %>
      </div>
    </td>
  </tr>
  <tr>
    <th><%= "詳細・補足" %></th>
    <td><%= @post.description %></td>
  </tr>
  <tr>
    <th><%= "お気に入り" %></th>
    <td>
      <% if favorited_by?(@post, current_user).present? %>
        <%= link_to post_favorites_path(@post.id), method: :delete do %>
          <i class="fa fa-thumbs-up fa-lg fa-fw" aria-hidden="true" style="color: red;"></i><%= favorited_by?(@post, current_user).size %>
        <% end %>
      <% else %>
        <%= link_to post_favorites_path(@post.id), method: :post do %>
          <i class="fa fa-thumbs-up fa-lg fa-fw" aria-hidden="true" style="color: gray;"></i><%= favorited_by?(@post, current_user).size %>
        <% end %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th><%= "ブックマーク" %></th>
    <td>
      <% if bookmarked_by?(@post, current_user).present? %>
        <%= link_to post_bookmarks_path(@post.id), method: :delete do %>
          <i class="fa fa-bookmark fa-lg fa-fw" aria-hidden="true" style="color: blue;"></i>
        <% end %>
      <% else %>
        <%= link_to post_bookmarks_path(@post.id), method: :post do %>
          <i class="fa fa-bookmark fa-lg fa-fw" aria-hidden="true" style="color: gray;"></i>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>

<br>

<%= form_with model: [@post, @reply] do |f| %>
  <%= f.label :reply, "リプライ" %>
  <%= f.text_area :reply, class: "form-control" %>
  <%= f.submit "リプライする", class: "btn btn-primary" %>
<% end %>

<br>

<% @replies.each do |reply| %>
  <% if reply.user_id == current_user.id %>
    <div class="text-end border-top border-dark">
      <%= reply.user.user_name %>
      <%= link_to "リプライ削除", post_reply_path(@post.id, reply.id), method: :delete, data: {confirm: "リプライを削除しますか？"},class: "card-link link-info text-decoration-none" %>
      <p class="bg-warning bg-opacity-50"><%= reply.reply %></p>
    </div>
  <% else %>
    <div class="border-top border-dark">
      <%= reply.user.user_name %>
      <p class="bg-secondary bg-opacity-25"><%= reply.reply %></p>
    </div>
  <% end %>
<% end %>