config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      root to: "posts#home"

      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/guest_login", to: "sessions#guest_login"
      delete "/logout", to: "sessions#destroy"

      namespace :admin do
        resources :users
      end

      get "/home", to: "posts#home"

      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resource :bookmarks, only: [:create, :destroy]
        resources :replies, only: [:create, :destroy]
      end

      resources :groups, except: :destroy do
        resources :group_users, only: [:create, :update, :destroy]
      end

      resources :notices, only: [:index, :update]
    end
  end
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "ユーザー詳細", admin_user_path(current_user.id) %></li>
          <li><%= link_to "ユーザー一覧", admin_users_path %></li>
          <li><%= link_to "ユーザー登録", new_admin_user_path %></li>
          <li><%= link_to "ログアウト", logout_path, method: :delete, data: {confirm: "ログアウトしますか？"} %></li>
        <% else %>
          <li><%= link_to "ユーザー登録", new_admin_user_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
    <% if current_user %>
      <div class="current-user-name"><%= "こんにちは，#{current_user.user_name} (id:#{current_user.id})さん" %></div>
    <% end %>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<div sidebar_fixed>
  <div class="d-flex flex-column flex-shrink-0 p-3 bg-light">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">LOGO</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <% unless current_user %>
        <li class="nav-item">
          <%= link_to "ゲストログイン", guest_login_path, method: :post %>
        </li>
        <li class="nav-item">
          <%= link_to login_path, class: "nav-link link-info" do %>
            <%= image_tag "login.png", size: "32x32", class: "me-2" %>
            <strong>ログイン</strong>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "ユーザー登録", new_admin_user_path %>
        </li>
        <li class="nav-item">
          <%= link_to "アプリ紹介" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ユーザーアイコン", admin_user_path(current_user.id), class: "nav-link link-info" %>
        </li>
        <li class="nav-item">
          <%= link_to home_path, class: "nav-link link-info" do %>
            <%= image_tag "home.png", size: "32x32", class: "me-2" %>
            <strong>ホーム</strong>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "画像一覧", posts_path, class: "nav-link link-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規投稿", new_post_path, class: "nav-link link-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "投稿絞り込み", class: "nav-link link-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "グループ編集", groups_path, class: "nav-link link-info" %>
        </li>
        <li class="nav-item">
          <%= link_to notices_path, class: "nav-link link-info" do %>
            <% if unchecked_notices.any? %>
              <span class="fa-stack">
                <i class="far fa-bell fa-stack-2x fa-fw" style="font-size: 1.5em;"></i>
                <i class="fas fa-circle fa-stack-1x fa-fw notice"><%= unchecked_notices.size %></i>
              </span>
            <% else %>
              <i class="far fa-bell fa-fw" style="font-size: 1.5em;"></i>
            <% end %>
            <span><%= "通知" %></span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "アプリ紹介", class: "nav-link link-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "アカウント詳細", admin_user_path(current_user.id), class: "nav-link link-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", logout_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: "nav-link link-info" %>
        </li>
        <hr>
        <li class="nav-item">
          <%= link_to admin_user_path(current_user.id), class: "nav-link link-info" do %>
            <%= image_tag current_user.user_avatar, size: "32x32", class: "rounded-circle me-2" if current_user.user_avatar.attached? %>
            <strong><%= current_user.user_name %></strong>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_message' %>
      <div class="col-2"><%= render 'layouts/sidebar' %></div>
      <div class="col"><%= yield %></div>
    </div>
    <%= include_gon %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>